name: Build and Push Docker Image to Alibaba Cloud ACR

on:
  push:
    branches: [ main ] # Or your preferred branch, e.g., master, release/*
  # You can also add other triggers like pull_request, workflow_dispatch, etc.
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Use a Linux runner
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Checks out your code

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Optional: For more advanced build features

      - name: Log in to Alibaba Cloud Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_REGISTRY_ENDPOINT }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # Build context (your repository root)
          file: ./Dockerfile # Path to your Dockerfile
          push: true # Actually push the image
          tags: ${{ secrets.ACR_REGISTRY_ENDPOINT }}/omh-fe/frontend:latest
          # Example: registry.cn-hangzhou.aliyuncs.com/my-namespace/my-node-app:latest
          # You can also use dynamic tags, e.g., with github.sha:
          # tags: |
          #   ${{ secrets.ACR_REGISTRY_ENDPOINT }}/your-acr-namespace/your-image-repo-name:latest
          #   ${{ secrets.ACR_REGISTRY_ENDPOINT }}/your-acr-namespace/your-image-repo-name:${{ github.sha }}